services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: immunilog.azurecr.io/backend:latest
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - immunilog-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: immunilog.azurecr.io/frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - immunilog-net

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ENV}
      MYSQL_DATABASE: immunilog
    ports:
      - "3306:3306"
    networks:
      - immunilog-net

networks:
  immunilog-net:
    driver: bridge
