services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: immunilog.azurecr.io/backend:latest
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - immunilog-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: immunilog.azurecr.io/frontend:latest
    ports:
      - "9000:80"
    depends_on:
      - backend
    networks:
      - immunilog-net

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Immunilog
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - immunilog-net

networks:
  immunilog-net:
    driver: bridge
