name: Build and deploy container app to Azure Web App - immunilog-back

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.19.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Verify repository structure
      run: |
        echo "Listing repository files..."
        ls -R

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: immunilog.azurecr.io
        username: ${{ secrets.AzureAppService_ContainerUsername_de437dc42d5a4b0d98ea3b75d4498f22 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1d11a6fb7dd64dffb23c75601fd5a828 }}

    - name: Build and push Docker images using Docker Compose
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'immunilog-back'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_047f7fb03c6647f2887c092b7bff3eab }}
        images: 'immunilog.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_de437dc42d5a4b0d98ea3b75d4498f22 }}/frontend:${{ github.sha }}'
