name: Build and Push Frontend Docker Image to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login
        run: |
          az acr login --name immunilog

      - name: Build the Docker image
        run: |
          docker build -t immunilog.azurecr.io/frontend-app:latest ./frontend

      - name: Push the Docker image to ACR
        run: |
          docker push immunilog.azurecr.io/frontend-app:latest

      - name: Clean up Docker images
        run: |
          docker rmi immunilog.azurecr.io/frontend-app:latest

      - name: Restart Azure App Service
        run: |
          az webapp restart --name immunilog-front --resource-group immunilog_group